on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          install.packages("pkgdown", dependencies = TRUE)
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install("waldronlab/curatedMetagenomicData", dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build site 
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Set up git 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
        shell: bash {0}

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
